name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
      # Install dependencies
      - run: npm install
      # Transform Figma Tokens JSON to something Style Dictionary can read
      - run: npx token-transformer tokens.json tokens/tokens.json global
      # Create a colors theme, exclude the global tokens
      - run: npx token-transformer tokens.json tokens/colors.json global,colors global
      # Create a typography theme, exclude the global tokens
      - run: npx token-transformer tokens.json tokens/typography-mobile.json global,typography-mobile global
      # Create a typograhpy theme, exclude the global tokens
      - run: npx token-transformer tokens.json tokens/typography-desktop.json global,typography-desktop global
      # Create a typography theme, exclude the global tokens
      - run: npx token-transformer tokens.json tokens/brand1-mobile.json global,colors,typography-mobile,brand1 global
      # Create a typograhpy theme, exclude the global tokens
      - run: npx token-transformer tokens.json tokens/brand1-desktop.json global,colors,typography-desktop,brand1 global
      # Create a typograhpy theme, exclude the global tokens
      - run: npx token-transformer tokens.json tokens/brand2-mobile.json global,colors,typography-mobile,brand2 global
      # Create a typography theme, exclude the global tokens
      - run: npx token-transformer tokens.json tokens/brand2-desktop.json global,colors,typography-desktop,brand2 global
      # Convert tokens according to Style Dictionary config
      - run: node build.js
      # Add files that were created during a run, e.g. created files from style dictionary or token-transformer.
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Tokens
